#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCwbxcPrHen1JArGJ8eFpwJg3f5PZS+tf2Knc2ScVtcDQ2XXEPoY3e5V+4cuIhkVO3dZJgaOqEl7LuWK4sFKZSLAmpZYBaUiG/J5sIvEfSLCp7tsmVEhob+aXi8n4duFfnrakAjbO9i6xmJj8/6+loGheRbtntrOdfx41yfJQjbB4wLZGBLmgWNj3o+GOFto7NGDmI3V74W6FmXgcTX6uBQVZ14gy/7wdsY4xqRK4G9tTcNmS0JzLxAUE3m8g0/8dB1fgbvqNtOCbBlAso2Oy+C+CDjGCtHrlfUdVAdgkx6749VOSi1tIHqvZq/cuuVDHKsob8gyOBIbPdKptBt9vPr aws-key
ssh_pwauth: false
disable_root: false
package_update: true
packages:
  - curl
  - wget
  - apache2
  - php
  - libapache2-mod-php
  
write_files:
  - path: /var/www/html/image.php
    content: |
        <?php 
        $ihrname = "Lukas"; ?>
        <html>
        <head>
        <title><?php echo($ihrname) ?></title>
        </head>
        <body>
            Auf dem Bild sehen wir eine USA-Flagge. Im Hintergrund koennen wir den Pazifik sehen, sowie die Suedkueste der Insel Oahu widerfinden.
        <br />
        <img src="https://lukasbucket1.s3.amazonaws.com/MicrosoftTeams-image.png" />
        Keine Quellenangaben notwendig, da das Bild von mir selbst aufgenommen wurde.
        </body>
        </html>
